version: '3.5'

services:
    http:
        image: nginx:latest
        restart: always
        depends_on:
          - node
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf

    node:
        restart: always
        entrypoint: npm
        command: run start:prod
