version: '3.5'

services:
    node:
        environment:
            NODE_ENV: production
        restart: always
        entrypoint: npm
        command: run start:prod
        ports:
          - ${DOCKER_HTTP_PORT}:8080

    npm:
        environment:
            NODE_ENV: production
